services:
  atlas:
    build: .
    container_name: project-atlas
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./:/host_project:ro
      - ./app:/app/app
      - ./main.py:/app/main.py
